version: '3.8'
services:
  im-redis:
    container_name: im-redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    privileged: true
    command: redis-server /etc/redis/redis.conf --appendonly yes
    volumes:
      - $PWD/redis/data:/data
      - $PWD/redis/conf/redis.conf:/etc/redis/redis.conf
    networks:
      - im-web
  im-mongo:
    container_name: im-mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - $PWD/mongodb/data/db:/data/db
      - $PWD/mongodb/data/log:/var/log/mongodb
      - $PWD/mongodb/data/config:/etc/mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - im-web
  im-mysql:
    container_name: im-mysql
    image: mysql:5.7.30
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      command:
        --default-authentication-plugin=mysql_native_password
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_general_ci
        --explicit_defaults_for_timestamp=true
        --lower_case_table_names=1
        --max_allowed_packet=128M;
    ports:
      - 3306:3306
    volumes:
      - $PWD/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - im-web

networks:

  im-web:
    driver: bridge
